### ISSUE TITLE
[Bug] Error after adding sass

### ISSUE THREAD

**Issue by teikirizi** [electron-vite/electron-vite-vue#322] opened 2022-12-14 17:43 UTC
npm create electron-vite
npm add -D sass
npm run dev

Got an error "failed to load config"

All good without the sass step

**Comment by xhayper** [comment] 2022-12-22 02:01
Caused by `dependencies` not existing in `package.json`

**Comment by xhayper** [comment] 2022-12-22 02:02
Should be fixed in #327

**Closed** 2022-12-22 08:04 UTC
Labels: bug
