### ISSUE TITLE
[Bug] Uncaught TypeError: Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by dongivan** [electron-vite/electron-vite-vue#212] opened 2022-07-25 03:52 UTC
#### Describe the problem you confuse

**2.0 template with vite3 build error while using Node.js API in renderer process**

There are some codes which should be compiled to `import.meta.url`, and they will be compiled to `{}.url` if `vite` (and `@vitejs/plugin-vue`) is upgraded to version 3 and Node.js API is enabled in the renderer process (by setting `renderer` to `{}` of the plugin `vite-plugin-electron`).
Maybe this has the same reason for the issue #210 ?

#### Errors

```log
Uncaught TypeError: Failed to construct 'URL': Invalid URL
```

**Comment by caoxiemeihao** [comment] 2022-07-29 07:03
This problem only occurs in `vite@3.x` with the `renderer` option enabled in `vite-plugin-electron`. The `renderer` option will [change the output-format](https://github.com/electron-vite/vite-plugin-electron/tree/main/packages/electron-renderer#config-presets-opinionated) of Vite tho `cjs`.

So the problem is when Vite builds `cjs` format, I will try to fix this with a plugin or submit a PR to VIte.

---

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/26263658/181699642-f7faa97d-8be4-4dad-99bf-f75f185ba2b7.png">

---

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/26263658/181700160-dcb2d0bb-755b-43a3-b458-3d18afd10a2a.png">

<img width="691" alt="image" src="https://user-images.githubusercontent.com/26263658/181700402-28927e3f-b0af-46e8-9eb2-db9b580b413b.png">

**Comment by caoxiemeihao** [comment] 2022-08-06 03:11
@dongivan @yooouuri Hey! 👋
This BUG will be fixed in #224
Nevertheless, `experimental.renderBuiltUrl` is currently an experimental API.
Looking forward to the next update of Vite.

**Closed** 2022-08-06 09:37 UTC
Labels: bug, help wanted
